name: Release
on:
  push:
    tags: ["*"]
env:
  PLUGIN_NAME: nuke-orphans
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: yarn

      - name: Run build
        run: yarn run build

      - name: Package
        run: |
          mkdir ${{ env.PLUGIN_NAME }}
          cp main.js manifest.json ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}

      - name: Update the latest release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          target_commitish: ${{ github.sha }}
          files: |
            ./${{ env.PLUGIN_NAME }}.zip
            ./main.js
            ./manifest.json
